### ISSUE TITLE
Unable to supress warnings

### ISSUE THREAD

**Issue by SeanSobey** [icsharpcode/RefactoringEssentials#100]
When trying to suppress some of the warnings (using the method suggested here: http://stackoverflow.com/questions/32130632/visual-studio-2015-turn-off-private-modifier-is-redundant-intellisense-war), I get an error "Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Static Analysis Tools\Rule Sets\MinimumRecommendedRules.ruleset' is denied." (Strange as well since I'm running VS2015, of course).

**Comment by christophwille** [comment]
12.0? VS 2015 is 14.0, so there is something weird going on.

**Comment by christophwille** [comment]
I cannot explain the 12.0 thing, but the in-built rulesets are read-only (regardless of VS version).

**Comment by SeanSobey** [comment]
So this not a valid way to suppress warnings? It has to be done at a project level like with GlobalSupress.cs?

**Comment by christophwille** [comment]
If you save it to a custom location, modifying an existing ruleset is ok.
