### ISSUE TITLE
"private modifier is redundant" is unbelievable!

### ISSUE THREAD

**Issue by NimaTheCoder** [icsharpcode/RefactoringEssentials#101]
According to c# coding style private modifier is not only redundant but also it is necessary! no option for turning it off is really annoying!

**Comment by christophwille** [comment]
https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers

**Comment by NimaTheCoder** [comment]
This is not same as turning it off!, I have more that 60 project in my current solution, should i do it manually for every project and for every new project!

**Comment by NimaTheCoder** [comment]
It's not same as turn it off! Should I do it for my current 60+ projects and every new project at future!

**Comment by NimaTheCoder** [comment]
How wonderful! Thanks so much.
