### ISSUE TITLE
RECS0134 is incorrectly raised

### ISSUE THREAD

**Issue by opiants** [icsharpcode/RefactoringEssentials#104]
In the code below, RECS0134 is raised for the _if_ statement. I only want to perform the mod call if I need to, hence the check. I personally don't agree that this is redundant. What if what's inside the if block is more expensive than a simple mod call?

	var expiryYear = someVariableFromMethodArgument;

	// Only get the last 2 digits
	if (expiryYear >= 100) // RECS0134?
	{
		expiryYear = expiryYear % 100;
	}

**Comment by oldlaurel** [comment]
+1
