### ISSUE TITLE
Lock analysis rule

### ISSUE THREAD

**Issue by Therzok** [icsharpcode/RefactoringEssentials#109]
Given a Field/Property x and a lock object y.

If at least once lock (y) is called to access x, then the other places are missing the locks.

**Comment by Kavignon** [comment]
Could someone provide a an example in code, I'm realy visual, and I can't quite see it in my head :(

**Comment by Therzok** [comment]
```
class A
{
    // Worst case, non-atomic on any kind of operation.
    long x;
    object obj = new object();

    void Inc()
    {
        lock (obj)
            x++;
    }

    void Dec()
    {
        lock (obj)
            x--;
    }

    void Add(int y)
    {
        // Signal that lock isn't being used here, since every other instance of the object had a lock on access (r/w).
        x += y;
    }
}

**Comment by Kavignon** [comment]
Perfect thanks, I'll get a new branch on my fork this week and get started with this. Except if I'm wrong, this shouldn't take long to implement ! @mkrueger  @Therzok

**Comment by Therzok** [comment]
Rules like this are getting implemented in dotnet/roslyn-analyzers.
