### ISSUE TITLE
CompareNonConstrainedGenericWithNullCodeFixProvider creates non-compilable code

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/RefactoringEssentials#112]
Something like

```
string DoSomethingElse<T>(T param)
{
      if (param == null) { }
}
```

will be converted to:

```
string DoSomethingElse<T>(T param)
{
      if (param == default(T)) { }
}
```

which will cause a compiler error
*CS0019: Operator '==' cannot be applied to operands of type 'T' and 'T'*

If `T` is a value type, then a "==" comparison is not generally applicable on it.

**Comment by Rpinski** [comment]
I've disabled the code fix for now, I don't think that `default(T)` is helpful here. Maybe there is a better idea?

**Comment by vbfox** [comment]
Well the correct transformation if the intention is to handle only nulls would be :

```
string DoSomethingElse<T>(T param)
{
      if (object.ReferenceEquals(param, null) { }
}
```

If the equality comparison is wanted it would be something more like :

```
string DoSomethingElse<T>(T param)
{
      if (EqualityComparer<T>.Default.Equals(param, default(T)) { }
}
```
