### ISSUE TITLE
RECS0021 complains about virtual call to private setter

### ISSUE THREAD

**Issue by piersh** [icsharpcode/RefactoringEssentials#121]
````
	public class Foo
	{
		public virtual string Prop { get; private set; }

		public Foo ()
		{
			this.Prop = "";
		}
	}
````
the setter here is private & can't be overridden, so it's OK to call from a constructor.

**Comment by piersh** [comment]
strangely, the warning goes away if i remove the 'this.'

**Comment by Rpinski** [comment]
Addressed both topics, private setter and difference with and without `this.`
