### ISSUE TITLE
RECS0163 is reported in Unity project (where nameof expression isn't supported)

### ISSUE THREAD

**Issue by dogfuntom** [icsharpcode/RefactoringEssentials#122]
~~It suggests to replace string literal with nameof, but it's not valid to do so, because .NET 3.5 Framework is too old to support that expression. To be more specific, my project has “Unity 3.5 .net full Base Class Libraries” as Target framework, which is pretty equivalent to usual .NET 3.5.~~
It suggests to replace string literal with `nameof` expression in Unity project, but Unity doesn't support such expressions, because it uses C# 3.

**Comment by paul1956** [comment]
I was under the impression that the compiler translated NameOf(X) to "X" why should that be effected by the .Net Version. When I tried it against .Net 3.5 client it seemed to work fine.

**Comment by dogfuntom** [comment]
Just tried it too, and you're right. Then it's all about Unity, it doesn't care about any compilers except that one integrated in it itself, and it's very old Mono compiler. I should probably rename and edit the issue then, shouldn't I?
In case you want to know more about an amount of people potentially affected by it, Unity is very popular (duh), and the latest version of it made VS 2015 a first class citizen IDE for Unity programming.

**Comment by Rpinski** [comment]
Hmm strange, since we have checks for language version in this analyzer:

https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/Diagnostics/Custom/NameOfSuggestionAnalyzer.cs#L47

**Comment by dogfuntom** [comment]
Okay, since you have shown me exact place, let me investigate it in the debugger.

**Comment by dogfuntom** [comment]
Yeah, it just says that it's CSharp6, plain lie.

**Comment by dogfuntom** [comment]
I wonder where language version value comes from. Is it Roslyn devs fault (maybe it's hardcoded and always CSharp6?) or UnityVS devs fault (some kind of wrong metadata in the generated .csproj files)?

**Comment by Rpinski** [comment]
From I've seen until now this value is influenced by language version setting in project itself:

*Project Properties -> Build -> Advanced... -> Language Version*

In .csproj file:

```
<PropertyGroup ...>
    <LangVersion>5</LangVersion>
  </PropertyGroup>
```
-> This configures C# 5 and hides RECS0163.

**Comment by dogfuntom** [comment]
Yep, there is no info about it in the content of .cproj file, so VS shows it as "default", which is C# 6. So, it's really UnitVS's fault to not generate fully correct project file.
