### ISSUE TITLE
Quick Action: Add XML documentation from parent class/interface

### ISSUE THREAD

**Issue by jumpinjackie** [icsharpcode/RefactoringEssentials#132]
It would be nice if when my cursor is on a public class member that has no XML documentation, if it is determined that the member is either:

 a) Overridden from a parent class
 b) Part of an implementation of an interface 

If either a) or b) has XML documentation attached to give me a Quick Action option to insert that same XML documentation to the currently focused member (and auto-rename any parameter references in the inserted XML doc if it is possible)

**Comment by siegfriedpammer** [comment]
Shouldn't `CopyCommentsFromBaseCodeRefactoringProvider` provide exactly that functionality? Can you give an example, where this does not work?

**Comment by jumpinjackie** [comment]
I was not aware this refactoring was available. Disregard.
