### ISSUE TITLE
Possible Issue with Warning RECS0019.  Not aware of new string interpolation?

### ISSUE THREAD

**Issue by dalenewman** [icsharpcode/RefactoringEssentials#142]
I changed this to an Info in my ruleset, but I think it's something that might need to be looked at.  See picture.

![visual-studio-2015-invalid-warning-interpolated-strings](https://cloud.githubusercontent.com/assets/933086/11104710/4c6df296-8898-11e5-8499-980da24aa267.png)

**Comment by Rpinski** [comment]
Thanks for reporting, looks like a bug from first sight. We'll investigate.

**Comment by Rpinski** [comment]
This is a bug in `SyntaxFactory.AreEquivalent()` in Roslyn itself: https://github.com/dotnet/roslyn/issues/5271.
When called on two interpolated string nodes it always considers them equivalent without checking their contents.

From what I see in Roslyn code, it seems to be fixed for upcoming releases: https://github.com/dotnet/roslyn/blob/Visual.Studio.2015.Update.1.RC/src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs#L81

**Comment by dalenewman** [comment]
Excellent.  Thanks.
