### ISSUE TITLE
Virtual member call in constructor - should this not go away if it's sealed?

### ISSUE THREAD

**Issue by Jaykul** [icsharpcode/RefactoringEssentials#146]
I have something like this in my class hierarchy:

```csharp
public abstract class DataGridViewModelBase<T> 
{
    // ...
    public abstract void RefreshData();
}

public class JobsViewModel : DataGridViewModelBase<Job>
{
    public JobsViewModel()
    {
            // ...
            RefreshData();
    }
    public override sealed async void RefreshData()
    {
            // ...
    }
}
```

This causes the **error**:

```
Severity	Category	Code	Description	
Error	Potential Code Quality Issues	RECS0021	Virtual member call in constructor
```

Now, I could be wrong, but it appears to me that since this method is marked sealed, it's not really virtual any more? Shouldn't sealing be enough to avoid this error? 

For what it's worth, sealing is the suggested "fix" from ReSharper when they flag similar problems.

**Comment by Rpinski** [comment]
Looks like you're right, a sealed overridden method shouldn't be dangerous.
