### ISSUE TITLE
CSharpTypeInferenceService.InferTypes methods obtained via reflection changed in Roslyn

### ISSUE THREAD

**Issue by DavidKarlas** [icsharpcode/RefactoringEssentials#147]
https://github.com/icsharpcode/RefactoringEssentials/blob/fe6fb675bf88b5f44e055505caf59640d446422c/RefactoringEssentials/Util/CSharpSyntaxContext.cs#L523-L538

https://github.com/dotnet/roslyn/commit/79c70b2b0d7eb1756d623a2e88430d8f5075c71f#diff-b5f3c2d218039b7d736e4d615a6dad30L15

**Comment by DavidKarlas** [comment]
I will add one more(ExpressionSyntaxExtensions.CastIfPossible):

https://github.com/dotnet/roslyn/commit/702127d648a6909020ea14d691c2ea8656598821#diff-a419a7e5e40e4a95b7469c2a47229a56R79

https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/Util/ExpressionSyntaxExtensions.cs#L47

This one breaks "Inline temporary variable" refactoring.

**Comment by Rpinski** [comment]
Hi David,

thanks for the hits. But `CSharpSyntaxContext` looks ok in current RE code, right? @siegfriedpammer has already fixed it for Roslyn 1.1.

`ExpressionSyntaxExtensions` indeed needs a fix (no `wasCastAdded` out parameter anymore). But the question is: Is this change already intended for Roslyn 1.1? It was made on master branch recently, 1.1 RC didn't contain it.

**Comment by DavidKarlas** [comment]
Hi Andreas,

MD uses Roslyn dlls built from roslyn master source code(bumped from time to time), so I'm not sure what version that would be...

I post this stuff here when I accidentally stumble into exception thrown, just to raise awareness.

I think @mkrueger will know best how to address this problem of syncing versions between Roslyn and RE...(maybe #ifdef, maybe git branches...)

**Comment by Rpinski** [comment]
At least it looks like Roslyn 1.2 won't contain `wasCastAdded` anymore: https://github.com/dotnet/roslyn/blob/version-1.2.0-beta-20151211-01/src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs#L83

**Comment by Rpinski** [comment]
Addressed in 1f00064510b35edafdf6d115bd5fd4be08fc9114.
