### ISSUE TITLE
Visual Studio 2015 - Update 1 -  Exception

### ISSUE THREAD

**Issue by wilhelmmedetz** [icsharpcode/RefactoringEssentials#152]
After installing the 'Visual Studio 2015" "Update 1" the following exception is display in the 'Error List' window.

Warning	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.CompareNonConstrainedGenericWithNullAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'RefactoringEssentials.SyntaxExtensions' threw an exception.'

**Comment by christophwille** [comment]
Are you using the released version from visualstudiogallery or the one from vsixgallery (test versions)? If the former, then the error is expected.

**Comment by wilhelmmedetz** [comment]
I am using the visualstudiogallery version - so I will wait for the next release.
