### ISSUE TITLE
Opt-in/opt-out mechanism for individual rules

### ISSUE THREAD

**Issue by tlycken** [icsharpcode/RefactoringEssentials#157]
I find this project really great, and it's definitely going to be a key piece of the puzzle I have to build to make VS work as I want it without depending on R#.

However, some of the rules (e.g. `RECS1029 'internal' modifier is redundant`) are in conflict with a different ruleset we enforce in my project through StyleCop analyzers, which requires all types to have an explicit access modifier. Thus, there's no way I can get both analyzers to stop reporting a fix there.

It would be awesome to have a checklist under Tools->Options somewhere, where I can check and uncheck various rules to decide which ones will be active. It should be possible to save these locally, in the project (for only me) or in the project (team-shared). It should also be possible to select "disable this rule" from the quick-action menu and not ever have to go to the options.

Maybe parts of this feature already exists, and I just can't find them, but I think this extension would be even more awesome if it was there.

**Comment by christophwille** [comment]
https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers

**Comment by tlycken** [comment]
@christophwille Nice! Not as easy to find as I would have liked, but works well (and, I realize, standardized for analyzers, so probably something most users will just have to learn to find anyway).

It would be awesome to add a suppress option to the quick actions, though. Although that might be something that VS has to do, rather than RefactoringEssentials?

**Comment by christophwille** [comment]
That would be a feature request for VS (or a power tool maybe that is x-analyzer libraries): eg "Suppress RECSxxxxx in current rule set"
