### ISSUE TITLE
Autogenerated code is scannded and throws errors

### ISSUE THREAD

**Issue by Bjego** [icsharpcode/RefactoringEssentials#160]
Hey guys,
we `re using Devart DotConnect for Oracle and the generated classes throw errors like 
RECS0021 C# Virtual member call in constructor

I think you are checking the headers of the generated files aren`t you?

Here is an example header:
//------------------------------------------------------------------------------
// <auto-generated>
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 10/28/2015 11:01:02 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

but in a constructor like this:
public Table_HI()
        {
          this.Generated= DateTime.Now;
          this.ChangeNumber= 1;
            OnCreated();
        }

throws RES0021.

How can I fix this?

**Comment by Rpinski** [comment]
Check was missing in this specific analyzer.
