### ISSUE TITLE
How to navigate next suggestion

### ISSUE THREAD

**Issue by beyaz** [icsharpcode/RefactoringEssentials#162]
is there any icon that can be focus next suggestion in file ? 
İn Resharper "Click to navigate next warning/suggestion" 
is there a similar property in RefactoringEssentials ? İf not , are you planing ?

**Comment by Rpinski** [comment]
Since all analyzer suggestions are shown in "Error List" panel, you can navigate through them using Visual Studio's shortcut `Ctrl+Shift+F12` ("Next error" command).
