### ISSUE TITLE
Apply a fix with a command?

### ISSUE THREAD

**Issue by sebas77** [icsharpcode/RefactoringEssentials#163]
Is it possible to apply a fix on the whole document through a command? I would like to run it when CodeMaid runs a format

**Comment by Rpinski** [comment]
Do you mean applying a code fix on all occurrences of an issue in whole document? Something like "Fix all occurrences in ..." as seen in following screenshot:

![Fix all occurrences](https://github.com/icsharpcode/RefactoringEssentials/wiki/images/RedundantExplicitArraySizeAnalyzer.png)

Most of our diagnostic analyzers have this feature.

**Comment by sebas77** [comment]
No, I mean if there is a command line command that I can type inside the CodeMaid box to run the "Fix all occurences in: Document" after the CodeMaid cleanup.

**Comment by christophwille** [comment]
We do not provide any infrastructure, this all comes from VS. And I don't know whether VS has it.
