### ISSUE TITLE
RECS0091 while using interface

### ISSUE THREAD

**Issue by Thaoden** [icsharpcode/RefactoringEssentials#166]
The following lines of code raise a RECS0091 in method `Baz()`:

	public interface IFoo { }

	public class Foo : IFoo { }

	public class Bar
	{
		public void Baz()
		{
			IFoo foo = new Foo();
		}
	}

However, `foo` is of type `IFoo`; when using the `var`-keyword, it is of type `Foo`, which changes the implementation.

**Comment by Rpinski** [comment]
I think your suggestion makes sense. We can fix it.
