### ISSUE TITLE
RedundantExplicitNullableCreationCodeFixProvider has encountered an error

### ISSUE THREAD

**Issue by ejohn54** [icsharpcode/RefactoringEssentials#169]
Getting this error from RedundantExplicitNullableCreationCodeFixProvider.
Looks like a NullReferenceException.

Here is sample code to reproduce the issue:
```
private void TraceHasValue(int? value)
{
    if (value.HasValue)
    {
        System.Diagnostics.Trace.WriteLine("HasValue");
    }
}
private void TestExplicitNullable()
{
    //Following line causes NullRef in RedundantExplicitNullableCreationCodeFixProvider
    TraceHasValue(new int?(2)); 
}
```

Below is the ActivityLog entry.

&lt;entry&gt;&#13;&#10;    &lt;record&gt;742&lt;/record&gt;&#13;&#10;    &lt;time&gt;2016/02/03 18:48:58.826&lt;/time&gt;&#13;&#10;    &lt;type&gt;Error&lt;/type&gt;&#13;&#10;    &lt;source&gt;RedundantExplicitNullableCreationCodeFixProvider&lt;/source&gt;&#13;&#10;    &lt;description&gt;Object reference not set to an instance of an object.&amp;#x000D;&amp;#x000A;   at RefactoringEssentials.CSharp.Diagnostics.RedundantExplicitNullableCreationCodeFixProvider.&amp;lt;RegisterCodeFixesAsync&amp;gt;d__3.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.&amp;lt;&amp;gt;c__DisplayClass13_0.&amp;lt;&amp;lt;AppendFixesAsync&amp;gt;b__2&amp;gt;d.MoveNext()&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown ---&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&amp;#x000D;&amp;#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&amp;lt;PerformFunctionAsync&amp;gt;d__3`1.MoveNext()&lt;/description&gt;&#13;&#10;&lt;/entry&gt;&#13;&#10;

**Comment by Rpinski** [comment]
Thank you for notifying, will be fixed!
