### ISSUE TITLE
'Error List' window gets polluted with warnings from analyzer exceptions

### ISSUE THREAD

**Issue by jlouros** [icsharpcode/RefactoringEssentials#170]
Hi there,

just started playing with Refactoring Essentials when I noticed a bunch of warnings that are not related with the project I'm working on. Most of the errors look like this:

`Analyzer 'RefactoringEssentials.CSharp.Diagnostics.CompareNonConstrainedGenericWithNullAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'RefactoringEssentials.SyntaxExtensions' threw an exception.'.`

![refactoring essentials bug](https://cloud.githubusercontent.com/assets/587250/12820387/d753e628-cb2c-11e5-913c-f2dca3b5052c.png)

Here's some additional details:
 - using Visual Studio 2015 with Update 1.
 - C# class library targeting .Net 4.5.2.
 - added Refactoring essentials as a NuGet package
 - changed the default rule sets (created a new *.ruleset file)

Let me know if I can help with anything.
Thanks

**Comment by christophwille** [comment]
Are you using today's 3.2 release? Because that should specifically address this issue.

**Comment by jlouros** [comment]
I was using version 3.1. After updating to 3.2 the vast majority the warnings disappeared, but there are still 3 warnings hanging around.

![refactoring essentials bug 2](https://cloud.githubusercontent.com/assets/587250/12827143/3ed22a34-cb4c-11e5-9391-a42456eb9602.png)

**Comment by Rpinski** [comment]
After some more code restructuring the warnings should have gone now.
