### ISSUE TITLE
"RECS0098: Remove redundant right side" reports incorrectly when left side is an equation

### ISSUE THREAD

**Issue by neoGeneva** [icsharpcode/RefactoringEssentials#172]
The following code reports RECS0098, and suggests I remove ` ?? b` from line 3, even though the code is correct since `(a + 1)` evaluates to null.

```csharp
decimal? a = null;
decimal? b = 2;
decimal? c = (a + 1) ?? b;
```

**Comment by Rpinski** [comment]
You're right, will be fixed.

**Comment by Rpinski** [comment]
@mkrueger Port of ConstantNullCoalescingConditionAnalyzer came with commit 08e45cfadbcf11e8ac4ce048feb862cd465a5f5e and it seems like the new `FlowAnalyzer` doesn't handle expressions like add/subtract/etc. at all. Maybe forward it to original submitter.

**Comment by mkrueger** [comment]
should be fixed
