### ISSUE TITLE
RECS0143 invalid with member variable

### ISSUE THREAD

**Issue by SteveOwensFDC** [icsharpcode/RefactoringEssentials#178]
Using v 3.2.0.0, here is the code that generated the message "The parameter 'moConfigSettings' can't be resolved."

```
        private List<ConfigData> moConfigSettings = null;
        ...
        
        public void ProcessConfigImport()
        {
            if (moConfigSettings == null)
            {
                throw new ArgumentNullException("moConfigSettings", "Config settings at application level must be specified to continue the import process.");
            }
        ...
```

**Comment by Rpinski** [comment]
The purpose of ArgumentNullException is (MSDN):

> The exception that is thrown when a null reference (Nothing in Visual Basic) is passed to a method that does not accept it as a valid argument.

So in the code above using ArgumentNullException and naming a non-existent method parameter is misleading for users of that method and therefore questionable. In my opinion the warning is correct.

**Comment by SteveOwensFDC** [comment]
I may misunderstand, but I thought that the idea of ArgumentNullException was to call out the _name_ of the variable that was null.  In this instance, the variable _name_ exists and so should not be the target of this warning.  I note that this warning goes away when using `nameof(moConfigSettings)` in place of the string.  But regardless of whether the hard-coded string or `nameof` is used, the variable's name should be able to be resolved.

**Comment by Rpinski** [comment]
According to [MSDN](https://msdn.microsoft.com/de-de/library/system.argumentnullexception%28v=vs.110%29.aspx) the idea of ArgumentNullException is to call out the name of a _method parameter_ that is null. In your example the method doesn't have any parameters. We could say RECS0143 is strictly following the convention where to use ArgumentNullException.

Wouldn't [InvalidOperationException](https://msdn.microsoft.com/de-de/library/system.invalidoperationexception%28v=vs.110%29.aspx) fit much better in this context?

> The exception that is thrown when a method call is invalid for the object's current state.

**Comment by SteveOwensFDC** [comment]
Okay, I see what you are saying about the doc.  InvalidOperationException is probably the best, but it’s so broad that it just doesn’t convey the nature of the problem.

In any event, thanks for the discussion.  I withdraw my issue.  ;-)

**Comment by Rpinski** [comment]
Thank you :-)
