### ISSUE TITLE
A number of refactorings failing

### ISSUE THREAD

**Issue by shanselman** [icsharpcode/RefactoringEssentials#18]
I'm getting these when working on the DasBlog source code. I'm in SharedBasePage.cs. It's lousy code, but it's still interesting I'm getting errors.

![image](https://cloud.githubusercontent.com/assets/2892/8560249/cd69ed50-24ca-11e5-8090-8c5a41bd5915.png)

**Comment by christophwille** [comment]
I take you were testing https://github.com/shanselman/dasblog - we'll take a look.

**Comment by Rpinski** [comment]
At least some issues seen with DasBlog solution have been addressed in 73b7f1fd387b4f03fc74d48ec01d671663d4cca5.

**Comment by Rpinski** [comment]
The error messages seen in screenshot will be fixed as soon as VS 2015 RTM is out.

**Comment by mkrueger** [comment]
I'll check that as well - next week I've some time working on RE. This week I was too busy :/
