### ISSUE TITLE
Newline character handling for "To interpolated string"

### ISSUE THREAD

**Issue by isaksky** [icsharpcode/RefactoringEssentials#182]
When it finds ```\n``` characters in the string, there is a problem where it evaluates them to actual newlines in the code, and the resulting code is not valid.

![newlines](https://cloud.githubusercontent.com/assets/607986/13291289/69c634dc-dad4-11e5-9450-560478ee4bb4.gif)

Best here would probably be to leave them in place. Failing that, to use the ```$@``` type strings.

**Comment by mkrueger** [comment]
fixed
