### ISSUE TITLE
Multiline strings when converting from C# to VB

### ISSUE THREAD

**Issue by ChadLevy** [icsharpcode/RefactoringEssentials#184]
In C# it's easy to have multi-line strings:

```c#
string sql = @"select * from giggles where id = 1
               order by name desc";
```

In VB 14, [multi-line strings are now supported](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-VB-14#multiline-string-literals):

```vb
Private sql As String = "select * from giggles where id = 1
                         order by name desc"
```

The converter, however, does this:

```vb
Private sql As String = "select * from giggles where id = 1" & vbLf & "                           order by name desc"
```

Edit: I don't know how to add a label to this but it should be `code converter`

**Comment by christophwille** [comment]
This is now live on the Web site
