### ISSUE TITLE
Getting Warning AD0001 with RedundantBaseQualifierAnalyzer and RedundantEmptyDefaultSwitchBranchAnalyzer

### ISSUE THREAD

**Issue by jakubsuchybio** [icsharpcode/RefactoringEssentials#186]
Hi,
- I searched and didn't find any similar error in your issues.
- I didn't search for reproduction of  this problem. If you need it I can debug it further with your assisence. I am sorry, but I can't send you our codebase.

Full error:
```
Severity    Code    Description Project File    Line    Suppression State
Warning AD0001  Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantBaseQualifierAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`8' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'.  RunUOPro        1   Active
```

Edit:
Also this one:
```
Severity    Code    Description Project File    Line    Suppression State
Warning AD0001  Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.  RunUOPro        1   Active
```

**Comment by christophwille** [comment]
Which version of VS (U1 or U2RC) and which version of RE are you using?

**Comment by Rpinski** [comment]
I've seen such exceptions when trying to use RE 3.2 (the official release) with Visual Studio 2015 Update 2 RC, caused by Roslyn incompatibilities 1.1 <-> 1.2.

**Comment by Rpinski** [comment]
@jakubsuchybio If this is your VS+RE constellation, then a possible solution for now is using one of recent development builds from [VSIXGallery](http://vsixgallery.com/extension/NR6Pack.Refactorings.Vsix..cd27e59b-5c56-4238-8931-c9bb745a7a7f/), which are ready for VS 2015 Update 2 RC and Roslyn 1.2.

**Comment by Rpinski** [comment]
Does it still happen with official 4.0 release? I've never seen this problem with VS 2015 U2 + RE 4.0.

**Comment by jakubsuchybio** [comment]
Yep.
Same problem with this diagnostics:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	RunUOPro		1	Active	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: RunUO
SyntaxTree: C:\dev\c#\manawydan\Scripts\Engines\Craft\Core\SelectCraftsManual.cs
SyntaxNode: switch( manual.RequiredRace ) { ... [SwitchStatementSyntax]@[46820..48287) (1417,3)-(1457,4)

System.NullReferenceException: Object reference not set to an instance of an object.
   at RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer.TryGetDiagnostic(SyntaxNodeAnalysisContext nodeContext, Diagnostic& diagnostic)
   at RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```
Here is the code: (problematic switch on line 72)
http://pastebin.com/VQmVWGVZ

I have version RE 4.0.0.0:
![image](https://cloud.githubusercontent.com/assets/6567287/14541851/3d6542d6-028c-11e6-904e-a75b8400ee3b.png)
And VS2015U2:
![image](https://cloud.githubusercontent.com/assets/6567287/14541989/f26861ea-028c-11e6-9baf-9898202ed904.png)

**Comment by Rpinski** [comment]
The exception with `RedundantEmptyDefaultSwitchBranchAnalyzer` seems to be the same as https://github.com/icsharpcode/RefactoringEssentials/issues/196, which is already fixed.
