### ISSUE TITLE
Problem of compilation

### ISSUE THREAD

**Issue by Urameshi78** [icsharpcode/RefactoringEssentials#189]
Hey, 

When I m trying to compile the project I have this error : 

3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3274: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.CodeAnalysis.CSharp.Desktop". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.CodeAnalysis.CSharp.Workspaces.Desktop". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.CodeAnalysis.Desktop". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

And I see these error are here too : 

https://ci.appveyor.com/project/icsharpcode/refactoringessentials/branch/master

and also on branch feature.

I don't understand why the project want to refer this assembly,  can you explain me if I'm doing something wrong or do something for fix this error pls 

Thx :)

**Comment by Rpinski** [comment]
Tests project has targeted wrong framework (4.5 instead of 4.5.2 needed by Microsoft.CodeAnalysis.Workspaces.Desktop). The references to missing ".Desktop" assemblies might have remained from older Roslyn versions.

**Comment by Urameshi78** [comment]
Ok thanks for yout help :)

**Comment by Urameshi78** [comment]
Hey, 

Now I have an another issue, I try to fix it but , it doesn't work 

C:\Users\myname\Desktop\RefactoringEssentials\packages\Microsoft.VSSDK.BuildTools.14.1.24720\tools\VSSDK\Microsoft.VsSDK.targets(655,5): error VSSDK1031: Extension 'NR6Pack.Refactorings.Vsix..cd27e59b-5c56-4238-8931-c9bb745a7a7f' could not be found. Please make sure the extension has been installed.

Have you an idea why it don't run 

Thx
