### ISSUE TITLE
RECS0033 suggestion produces bad code fix at xor-assignments

### ISSUE THREAD

**Issue by neofuji** [icsharpcode/RefactoringEssentials#192]
The code:
```
if (foo)
{
    bar ^= true;
}
```
produces a suggestion RECS0033 Replace with '|='.

Doing the fix produces:
```
bar |= foo;
```
It is not correct. I want to invert bar, but it will not assign `false`.

Also,
```
if (foo)
{
   bar ^= false;
}
```
produces a suggestion RECS0093 Replace with '&='.

Doing the fix produces:
```
bar &= !foo;
```
It is not correct.

**Comment by Rpinski** [comment]
Thank you for reporting!
