### ISSUE TITLE
LocalVariableHidesMemberAnalyzer doesn't format the description message

### ISSUE THREAD

**Issue by Therzok** [icsharpcode/RefactoringEssentials#193]
https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/Diagnostics/Synced/CodeQuality/LocalVariableHidesMemberAnalyzer.cs#L16

This is coming out as just `Local variable '{0}' hides {1} '{2}'` instead of having variable names.

**Comment by Rpinski** [comment]
Thanks for reporting!
