### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by liamhughes** [icsharpcode/RefactoringEssentials#194]
Hello,

I have just installed the extension but have no idea how to use it and I cannot find any documentation on it.

I assume that if I access quick actions (Ctrl+.) it will show up, and I saw something about warnings?

Maybe the extension is not working. Any tips on troubleshooting?

I have tried testing with the following:

```cs
var foo = true;
var bar = true;

if (foo)
{
    if (bar)
        Console.WriteLine("foo");
}
```

I expect it to recommend merging the nested 'if'.

Thanks.

**Comment by Rpinski** [comment]
Tried your code example and this is exactly what happens here: Set cursor on one of the "if"s and press `Ctrl+.` => There is a "Merge nested 'if'" entry in bulb menu, which does what you expect.

Do you see any warnings in Error List numbered with "RECSxxxx"? Which version of Refactoring Essentials have you installed? Which version of Visual Studio do you use?

**Comment by liamhughes** [comment]
Thanks for the reply.

I have updated to Visual Studio 2015 Update 1 (hadn't realised I wasn't updated), and it seems to be working now.

For future reference, before I updated:
- When I `Ctrl+.` a message at the bottom of the window says, "No quick actions available here".
- No RECS warnings.

**Comment by Rpinski** [comment]
Then I think we can close this now.

**Comment by liamhughes** [comment]
Yes, thank you for your time.
