### ISSUE TITLE
"Redundant cast" false positive on division expression

### ISSUE THREAD

**Issue by jumpinjackie** [icsharpcode/RefactoringEssentials#195]
Using Refactoring Essentials 3.2 on VS 2015 Update 1 on Windows 8.1

I have a property like this:

        public double Ratio
        {
            get
            {
                if (TotalCount == 0)
                    return 0;

                return (double)SubTotal / (double)TotalCount;
            }
        }

Where TotalCount and SubTotal are other int properties in the class

Both double casts are being reported as redundant by RE, but removing the casts as suggested by RE alters the semantics of the division operation, turning it into an int/int division result (that will always be an int) that is converted up to double instead of a double/double division result which is what I want.

**Comment by Rpinski** [comment]
Tested with VS 2015 Update 2 and latest RE development build: The message about redundant cast is a "IDE0004", which is one of Roslyn's built-in analyzers.
