### ISSUE TITLE
"RECS0117 Local variable '' hides member ''" shouldn't consider classes to be "members"

### ISSUE THREAD

**Issue by neoGeneva** [icsharpcode/RefactoringEssentials#198]
The following code reports "RECS0117 Local variable 'entity' hides member 'entity'", even though entity is still referenceable as a type:

``` csharp
public class SomeClass
{
    public void Test()
    {
        var entity = 123;
        var x = new entity();
    }
}

public class entity
{
}
```

**Comment by Rpinski** [comment]
Thanks for reporting, should be fixed now.

**Comment by neoGeneva** [comment]
Hey @Rpinski, I've just installed "Refactoring Essentials for Visual Studio 2017" v5.2.0.0  and it looks like this bug has returned.
