### ISSUE TITLE
Parameters for xml doc comment are not found any more

### ISSUE THREAD

**Issue by bexxx** [icsharpcode/RefactoringEssentials#201]
/// <summary>
        /// The generic event handler for messaging events.
        /// </summary>
        /// <typeparam name="TEvent">The event type of this event.</typeparam>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The event argument containing the slack event itself.</param>
        public delegate void EventHandler<TEvent>(object sender, SlackEventArgs<TEvent> e);

Error	 RECS0081	Parameter 'sender' not found	
Error RECS0081	Parameter 'e' not found	

This is new since the update to VS2015 Update 2.

**Comment by olathunberg** [comment]
I have a fix ready for this issue. Will make a pull request in an few days.

**Comment by Rpinski** [comment]
Ola has fixed this one in 4aa927a9dbcfd0af9f18f3b9934cd8bfbf713643.
