### ISSUE TITLE
RECS0135 null conditional bug

### ISSUE THREAD

**Issue by Tydude4Christ** [icsharpcode/RefactoringEssentials#202]
For a recursive function that only calls itself with the null conditional operator this warning is incorrectly displayed as in the below example.

    void IncrementCount(int amount)
    {
        Count += amount;
        Parent?.IncrementCount(amount);
    }

but not with this

    void IncrementCount(int amount)
    {
        Count += amount;
        if (Parent != null)
        {
            Parent.IncrementCount(amount);
        }
    }

**Comment by Rpinski** [comment]
Should be fixed now, thanks for reporting!

**Comment by Tydude4Christ** [comment]
Great, thank you. I'm really impressed with this extension, keep up the good work.
