### ISSUE TITLE
Disable analysis in GeneratedCode

### ISSUE THREAD

**Issue by neofuji** [icsharpcode/RefactoringEssentials#203]
Could you disable analysis in classes with `System.CodeDom.Compiler.GeneratedCodeAttribute`?

Here is an example:
```
// -----------------------------------------------------------
//  
//  This file was generated, please do not modify.
//  
// -----------------------------------------------------------
namespace EmptyKeys.UserInterface.Generated {
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.ObjectModel;
    using EmptyKeys.UserInterface;
    using EmptyKeys.UserInterface.Charts;
    using EmptyKeys.UserInterface.Data;
    using EmptyKeys.UserInterface.Controls;
    using EmptyKeys.UserInterface.Controls.Primitives;
    using EmptyKeys.UserInterface.Input;
    using EmptyKeys.UserInterface.Interactions.Core;
    using EmptyKeys.UserInterface.Interactivity;
    using EmptyKeys.UserInterface.Media;
    using EmptyKeys.UserInterface.Media.Animation;
    using EmptyKeys.UserInterface.Media.Imaging;
    using EmptyKeys.UserInterface.Shapes;
    using EmptyKeys.UserInterface.Renderers;
    using EmptyKeys.UserInterface.Themes;
    
    
    [GeneratedCodeAttribute("Empty Keys UI Generator", "2.1.0.0")]
    public partial class BasicUI : UIRoot { // causes RECS0001
        
        private Grid e_0;
        
        private ListBox e_1;
        
        public BasicUI() : 
                base() { // causes RECS0126
            this.Initialize();
        }
```

**Comment by Rpinski** [comment]
Since release 1.2 Roslyn is able to detect generated code, but we'll have to configure every single analyzer to use this feature instead of our own implementation. We'll try to finish this work for next release.

**Comment by Rpinski** [comment]
Latest changes on master branch should have covered all analyzers, so now it's up to Roslyn to detect generated code correctly. This also includes your case.

**Comment by paul1956** [comment]
Do you know where to find the documentation on how to use Roslyn to detect generated code AND how I might use it in my analyzer?

**Comment by Rpinski** [comment]
Here's the commit which has introduced the feature with description:

https://github.com/mavasani/roslyn/commit/f876a57fddffe64399e90e9291c214328f80a181

**Comment by ddobrev** [comment]
@Rpinski has mavasani/roslyn@f876a57 been merged to any of the released updates for VS 2015? I have a generated file starting with <auto-generated>, I have also added GeneratedCodeAttribute but RefactoringEssentials analyses the file anyway when I open it.

**Comment by Rpinski** [comment]
AFAIK it's part of Roslyn 1.2 and therefore VS 2015 Update 2.

**Comment by ddobrev** [comment]
I see, so it shouldn't analyse after all. I'll send you my generated file to test with tomorrow.

**Comment by ddobrev** [comment]
[QtCoreSharp.zip](https://github.com/icsharpcode/RefactoringEssentials/files/277453/QtCoreSharp.zip)

QtCore.cs in the attached project starts with // <auto-generated> and has CodeGenerated, both in AssemblyInfo and on each type. Nevertheless, when I open this file, devenv.exe memory goes rapidly up. I don't know whether I have placed the attributes or the tag incorrectly or whether that Roslyn commit has not been released or whether Refactoring Essentials ignores markers for generated code. Therefore I'd like to ask you to test and let me know what the problem is.
My Visual Studio is Update 2 plus the micro update from https://msdn.microsoft.com/en-us/library/mt695655.aspx.

**Comment by Rpinski** [comment]
I've tested your solution: As soon as the file contains `<auto-generated>` in comment, there are no RE analyzer warnings anymore ("RECSxxxx"). I only see 215 of Roslyn's built-in "CSxxxx" warnings. When removing `<auto-generated>`, the RE warnings appear as well.

**Comment by ddobrev** [comment]
I see. Does memory usage do up for you? In other words, does Roslyn itself ignore &lt;auto-generated&gt; unlike RE?
