### ISSUE TITLE
ignore RECS0091  (C# Use 'var' keyword) for multiple declarations

### ISSUE THREAD

**Issue by livioc** [icsharpcode/RefactoringEssentials#207]
when there are multiple declarations as

`DataTime time0 = new DateTime(2015,1,1),
      time1 = new DateTime(2015,1,1);`

the refactoring to use 'var' will broke the code because it cannot compile (Implicitly-typed variables cannot have multiple declarators) so it's better if the code analysis will ignore this case

**Comment by Rpinski** [comment]
Thank you for sharing that, should be fixed for next release.
