### ISSUE TITLE
RECS0002 - Incorrectly identifies Lambda Simplifications

### ISSUE THREAD

**Issue by smudge202** [icsharpcode/RefactoringEssentials#21]
There was some weirdness going on here, but the analyser suggested the following line as an `RECS0002` candidate:

https://github.com/smudge202/compose/blob/dev/tests/Compose.Tests/TransitionTests.cs#L248

The resulting refactor was not compilable, but that was because the simplification changed the delegate signature from `Action` to `Func<T1, T2>`, which in turn switched to a different overload in xUnit which was deprecated. Point being though, the refactor changed the signature, which should not happen.

**Comment by Rpinski** [comment]
Could you post how this line looked like after applying the refactoring?

**Comment by herecydev** [comment]
This will resolve to

```c#
Assert.Null(Record.Exception(app.Transition<IDependency, OtherDependency>));
```

A simplified example will work if you do:

```c#
Foo(app.Transition<IDependency, OtherDependency>);

private void Foo(Action act) { }
```

But when this is extended to

```c#
Foo(app.Transition<IDependency, OtherDependency>);

private void Foo(Action act) { }

private void Foo(Func<object> act) { }
```

This is an overload resolution issue (it can't determine which overload to use as they are both equally "good"). Lambdas and method groups have different rules, which is why when keeping the lambda we are able to resolve the correct overload.

**Comment by Rpinski** [comment]
I hope this is a proper solution for this special case. If you see more problems, feel free to reopen.

**Comment by herecydev** [comment]
I'm not sure what you mean by that; you need to have a thorough understanding of the specification and how the compiler is operating to be doing this. I can't tell you if that's the correct/only solution, only that it's what I understand from my *limited* knowledge.
