### ISSUE TITLE
Conversion of VB.NET to C#

### ISSUE THREAD

**Issue by twenzel** [icsharpcode/RefactoringEssentials#211]
Now you have a great Roslyn based converter for C# to VB.NET conversion. Are there any plans to create a converter for VB.NET to C#?

Do you already have started with anything like that? Do you need support, I might could take some parts if necessary.

**Comment by christophwille** [comment]
Please see https://github.com/icsharpcode/RefactoringEssentials/blob/master/converter.txt

It is not implemented (not even started). It is basically up for grabs as @siegfriedpammer definitely won't have time the next two quarters to do any meaningful work.

**Comment by twenzel** [comment]
Thanks for clarification. I might have a look at the current converter and try to figure out how to start with an vb to c# converter.
If anyone have hints or notes, you're welcome.

**Comment by siegfriedpammer** [comment]
Yes, I would start by implementing it in the same way as the C#2VB converter. As @christophwille mentioned, I am currently doing a lot other things, but I might be able to take a look at your PRs and give feedback before merging them. But, please keep in mind that I might not have the time to respond immediately.

**Comment by kelps** [comment]
Now we're talking! I'll see if I can find the time to help with this as well. I am very interested in converting our company's code base from VB to C# and the only thing missing to convince my boss is a reliable piece of software to do the work (at least the bulk of it). It's been over 5 years that I've wanted to do this, maybe now I'll finally be able to do it.

**Comment by twenzel** [comment]
@kelps That's exactly my story ;)
Let's use my [repository](https://github.com/twenzel/RefactoringEssentials) as new "master". I already started and successfully passed the first unit test. Let's discuss further on [gitter](https://gitter.im/twenzel/RefactoringEssentials?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by siegfriedpammer** [comment]
Conversion of VB.NET to C# was implemented in 7c9fed45d961554627e3957edfdcc120d2063857 and the following commits.

**Comment by rgish** [comment]
Another option: https://github.com/wbennett/DotNetTranslator
