### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hughgallagher** [icsharpcode/RefactoringEssentials#214]
The Wiki has no info on how to install this extension. Can it be installed at solution level or does it have to be installed per project?

**Comment by Rpinski** [comment]
There are 2 options:

* Installation on application level in VIsual Studio: Search for "Refactoring Essentials" in Visual Studio's "Extensions and Updates" dialog and install it as any other VS extension.
* Installation as NuGet package (search for "Refactoring Essentials" in official NuGet repository). NuGet packages can be installed only on project level, but in VS you can manage packages for multiple projects at once by selecting "Manage NuGet Packages for Solution..." in a solution's context menu.

Hope that helps.

**Comment by Rpinski** [comment]
Do you need more information or assistance?
