### ISSUE TITLE
'accessor never reaches end or a return statement' incorrect warning

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/RefactoringEssentials#219]
Posting from [JustinMinnaar](https://visualstudiogallery.msdn.microsoft.com/site/search?f%5B0%5D.Type=User&f%5B0%5D.Value=JustinMinnaar) on Visual Studio Gallery:

*Given the following code, I receive the 'accessor never reaches end or a return statement' warning on the get function of the Caption property, yet my code appears to be correct, and works correctly.*

```cs
public string caption
{
      get { return TryGetString(nameof(caption)); }
      set { SetString(nameof(caption), value); }
}
```

**Comment by vaindil** [comment]
@Rpinski I'm getting this error now as well, I'm on 4.2.0.0. (It's from Refactoring Essentials, disabling the extension makes the warning disappear.) .NET Core, VS 2015 Enterprise Update 3.

```csharp
public class BaseController : Controller
{
    protected CurrentUser CurrentUser
    {
        get
        {
            var id = 0;
            var idSucceed = int.TryParse(User.FindFirst(ClaimTypes.Id).Value, out id);
            CurrentUser.Id = id;

            CurrentUser.Email = User.FindFirst(ClaimTypes.Email).Value;
            CurrentUser.FirstName = User.FindFirst(ClaimTypes.FirstName).Value;
            CurrentUser.LastName = User.FindFirst(ClaimTypes.LastName).Value;
            CurrentUser.Username = User.FindFirst(ClaimTypes.Username).Value;

            return CurrentUser;
        }
    }
}
```

**Comment by Rpinski** [comment]
@vaindil What exactly is `CurrentUser` you are referring inside of the get accessor block?
