### ISSUE TITLE
When loading RefactoringEssentials as a nuget package, building from the commandline will fail to load analyzers

### ISSUE THREAD

**Issue by jmarolf** [icsharpcode/RefactoringEssentials#221]
RefactoringEssentials has a dependency on the Workspaces layer of roslyn.  This dll is not loaded by the commandline compiler, only Visual Studio.  As a result the analyser will fail to load at compiler time.

Severity | Code | Description
------ | ------- | -------
Warning	|  |	Analyzer 'RefactoringEssentials.CSharp.RoslynUsageAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.

**Comment by Rpinski** [comment]
Funny, that this analyzer's purpose is to detect exactly this case in Roslyn code...

**Comment by Rpinski** [comment]
I've fixed that by disabling this analyzer for now (it's only intended as helper for RE development, anyway). Finally we'll need to decide if separation into multiple assemblies (and packaging only one part for NuGet) is the only way to solve that.
