### ISSUE TITLE
Wrong suggestion on Linq

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#224]
I have:
`foreach (var r in results.Where(r => r.EndsWith(Ready, true, CultureInfo.CurrentCulture)))`

and get a correction proposal as:

`foreach (var r in results.Where(r => r.EndsWith(Ready, true, CultureInfo.CurrentCulture, StringComparison.Ordinal)))`

wich generates naturaly: "Error CS1501 No overload for method 'EndsWith' takes 4 arguments"

**Comment by Rpinski** [comment]
Should be fixed in next release, thank you for reporting!
