### ISSUE TITLE
Dangerous suggestion

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#225]
For:
`if (_selectedInd > -1) { DGV_Main.Rows[_selectedInd].Selected = true; }`
the suggestion is to 
"Replace with '|='" resulting:
`DGV_Main.Rows[_selectedInd].Selected |= _selectedInd > -1;`
, which would allow  "_selectedInd <= -1" resulting exception.

**Comment by Rpinski** [comment]
Should be fixed on development branch, thank you!
