### ISSUE TITLE
readonly proposal despite usage

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#226]
I have "Size _bufferSize;"

and a usage later on:
`bufferSize.Width = value.Width;`

but I get a proposal of "readonly Size _bufferSize;"

that causes:
"Error	CS1648	Members of readonly field 'GDISurface._bufferSize' cannot be modified (except in a constructor or a variable initializer)"

**Comment by Rpinski** [comment]
This should be fixed now.
