### ISSUE TITLE
False positive for RECS0135 (method does not reach end/return)

### ISSUE THREAD

**Issue by bexxx** [icsharpcode/RefactoringEssentials#229]
public sealed class Schema
    {
        public override bool Equals(object obj)
        {
        ...
        }

        public override int GetHashCode()
        {
            return (lots of xor'ed values) ...
        }

I get the error on GetHashCode. Interestingly only in one class, not all classes where I override GetHashCode.
It seems it happens when GetHashCode is called on fields of the same type (Schema in this case above).

**Comment by Rpinski** [comment]
You mean you have something like this:

```
public sealed class Schema
{
    private Schema otherSchema;

...

    public override int GetHashCode()
    {
        return ... otherSchema.GetHashCode() ...;
    }
}
```

?

**Comment by Rpinski** [comment]
I've fixed an issue here (see my code example above) and I hope it was yours :-)
