### ISSUE TITLE
Crash when applying refactoring to more than document level

### ISSUE THREAD

**Issue by JaCraig** [icsharpcode/RefactoringEssentials#23]
This may just be a Visual Studio bug. Wasn't able to find it in their list though but applying any of the suggested changes to the project or solution as a whole crashes Visual Studio.

**Comment by Rpinski** [comment]
At least I can't reproduce any crash on my VS 2015 RC (Win 8.1). If I understand correctly you have that issue with every kind of code fix? Can you give an example?

**Comment by JaCraig** [comment]
Finally got back my internet today... Got to love Comcast. Anyway, figured this one out. Seems to actually be an issue with CodeMaid's interaction with the code refactoring, not RefactoringEssentials. Turned off CodeMaid and the issue went away.

**Comment by Rpinski** [comment]
Thx for the info!
