### ISSUE TITLE
Missing var proposal for char

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#231]
`char ch = ' ';`

Dosn't trigger a proposal for use "var".

**Comment by mkrueger** [comment]
It's always a problem what to propose - for many people that's too much.
They want int foo = 5; without the suggestion.

I agree that in that case it doesn't increase readability in any way.So we decided not to warn in that case (after some discussion)

However we'll propose 'var' in such case:

char ch = (char)12;

**Comment by FickoDeLux** [comment]
ok, see the point.
