### ISSUE TITLE
C#->VB.NET - AddressOf is missing

### ISSUE THREAD

**Issue by beppe9000** [icsharpcode/RefactoringEssentials#234]
I don't know if this is the right place but I believe it is. 

I tried to convert the following example snippet with the [Roslyn Code Converter](https://roslyncodeconverter.azurewebsites.net/) but it is not translated properly.

```
public void Run()
{
    // Start the render loop
    RenderLoop.Run(renderForm, RenderCallback);
}

private void RenderCallback()
    {
        // I'm a comment. I will die after conversion.
    }
```

This is the result:

```
Public Sub Run()
```

**`RenderLoop.Run(renderForm, RenderCallback)`**

```
End Sub

Private Sub RenderCallback()
End Sub
```

And this is the expected result, using the `AddressOf` keyword to get the reference to the `RenderCallback` sub.

```
Public Sub Run()
```

**`RenderLoop.Run(renderForm, AddressOf RenderCallback)`**

```
End Sub

Private Sub RenderCallback()
End Sub
```

**Comment by GrahamTheCoder** [comment]
I have some code which makes a start on fixing this in the vb to csharp direction, will pr it soon in the new repo

**Comment by christophwille** [comment]
Now tracked in the CC repository https://github.com/icsharpcode/CodeConverter/issues/18
