### ISSUE TITLE
RECS0021 - 'Virtual member call in constructor' false positive

### ISSUE THREAD

**Issue by steveniles** [icsharpcode/RefactoringEssentials#237]
Example code:

    using System.Threading.Tasks;
    namespace ConsoleApplication1
    {
        public abstract class ExampleBase
        {
            private readonly Task operationTask;
            protected ExampleBase()
            {
                this.operationTask = new Task(this.OperationBody);
            }
            protected abstract void OperationBody();
            public void RunOp() => this.operationTask.RunSynchronously();
            public void RunOpAsync() => this.operationTask.Start();
        }
    }

`this.OperationBody` get's marked as a virtual member call in the constructor when it's really just a reference, not a call. The call doesn't happen until after the constructor is finished (if it is ever called at all)

I don't know if it's feasible in less trivial code to tell if the call does (or could) end up being called later in the constructor, so removing the warning might not be as good an idea as having a different warning for this scenario..

**Comment by Rpinski** [comment]
Yes, maybe separating this case as a different analyzer or at least using a different warning text would make sense.

**Comment by nvmkpk** [comment]
There is no need for warning in this case. There is no easy way to determine if the delegate to virtual method is being called from within constructor. This analyzer does not detect indirect calls to virtual method (through another non-virtual method called in the constructor) anyway. There advanced cases are best suited for in analyzers that run at runtime.
