### ISSUE TITLE
C# coding style and standards!

### ISSUE THREAD

**Issue by nimanzd** [icsharpcode/RefactoringEssentials#239]
Every language has its own coding style. Consistent style and formatting help developers avoid common pitfalls and mistakes. [CSharpCodingStandards.pdf](http://se.inf.ethz.ch/old/teaching/ss2007/251-0290-00/project/CSharpCodingStandards.pdf) is the most comprehensive document on c# coding style.

Unfortunately RefactoringEssentials does not follow C# coding style! (somehow!)

For example, according to [this](https://msdn.microsoft.com/en-us/library/ff926074.aspx?f=255&MSPPError=-2147217396) guild line:

```
var var1 = "This is clearly a string."; //right
var var4 = ExampleClass.ResultSoFar(); //wrong, becuase the type of var4 is not obvious!
```

Another example:
Fields are private variables named by an underscore + camelCase style. like:
`private string _connectionString;`

So developers can easily distinguish between fields (_camelCase) , local variables (camelCase) and properties (PascalCase), with a glance of look!

**Comment by Rpinski** [comment]
Are you talking about code of RE or about the code generated by RE?

**Comment by nimanzd** [comment]
Suggestions and Code generated by RE. For example: Initialize code by field neither add private nor underscore.

**Comment by IanKemp** [comment]
Why should we arbitrarily use a coding standard that one guy dreamed up, instead of [Microsoft's own internal ones](https://blogs.msdn.microsoft.com/brada/2005/01/26/internal-coding-guidelines/)? Which BTW, explicitly state:

"Do not use a prefix for member variables (_, m_, s_, etc.). If you want to distinguish between local and member variables you should use “this.” in C# and “Me.” in VB.NET."

**Comment by nimanzd** [comment]
Look at the references in CSharpCodingStandards.pdf they are all Microsoft guideline. One guy gathered not dreamed!
-  [Another](https://msdn.microsoft.com/en-us/library/ff926074.aspx?f=255&MSPPError=-2147217396) guildline from msdn.
- [aspnet](https://github.com/aspnet/) projects. Entity Framework for example.They are Microsoft projects.
- Your commercial alternatives Resharper. 

All of them follow CSharpCodingStandards.pdf

**Comment by Rpinski** [comment]
You already see it: Every coding guideline is just a guideline. As soon as we implement it, the next user will complain about RE not considering their project's code style, damaging their code base etc. The best solution is to make the code style configurable, so RE can respect the project's individual requirements. As far as I know this is what MS is planning to introduce in VS soon.

**Comment by nimanzd** [comment]
I didn't complain, just suggest the most used coding style even by Microsoft. I'm happy with coderush.

**Comment by nvmkpk** [comment]
I agree with @IanKemp and @Rpinski. Every team within Microsoft don't use one standard coding guidelines. These things should be configurable.

**Comment by epignosisx** [comment]
It would be nice if this could be configurable to accommodate different teams styles.

**Comment by nimanzd** [comment]
There is only one coding style for every language, the configuration is meaningless, wast of time. if you have't noticed it you should choose another career.

**Comment by christophwille** [comment]
The next version of VS has code styles and applies it to analyzer-generated code. 

And BTW. Please keep the discussion cordial.

**Comment by epignosisx** [comment]
@christophwille thanks for heads up. Then it doesn't make sense to invest in making it configurable.

**Comment by MortenChristiansen** [comment]
@christophwille I assume that you are talking about the EditorConfig support? It seems quite limited in its configuration options. As far as I can gather, the complete set of rules are show here: https://github.com/dotnet/roslyn/blob/master/.editorconfig

For example, there is no way to make method parameters create a backing field in the format `private readonly int _myValue;` which is what I use. Having to constantly rewrite from `readonly int myValue` (and the associated `this.myValue` to `_myValue`) is driving me nuts and might drive me to look elsewhere for refactorings.

**Comment by christophwille** [comment]
I did mean code styles. Tools / Options, Text Editor / C# / Code Style

**Comment by nimanzd** [comment]
I migrated to [Roslynator](https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator)
**It supports Microsoft c# coding style.** I suggest you do too!

**Comment by IanKemp** [comment]
LOL, I also migrated to Roslynator many moons ago because Refactoring Essentials didn't have a VS2017-compatible extension until after RTM.

**Comment by MortenChristiansen** [comment]
@christophwille Nice, I hadn't seen that. However, the refactorings in RE does not respect these settings. Instead, I just get code that does not compile (if I set the code style to be enforced by the compiler).
