### ISSUE TITLE
Ability to enable/disable specific checks via global settings

### ISSUE THREAD

**Issue by ravensorb** [icsharpcode/RefactoringEssentials#24]
It would be great if it was possible to enable/disable specific checks at a global level. For example, I do not want to use "nameof" -- so there should be a way to turn off RECS0164

**Comment by mkrueger** [comment]
That's part of the IDE to do.

**Comment by christophwille** [comment]
Please see https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers

"Global" per se doesn't exist, but you can create your personal "global" rule set that you apply to all your projects.
