### ISSUE TITLE
Removing ToString is too relaxed

### ISSUE THREAD

**Issue by bexxx** [icsharpcode/RefactoringEssentials#248]
I was forced to work on a completely fucked up codebase written by some #$%$#%@#$ and they were shadowing public string ToString() and called that one on some instances.

The refactoring tool did not check if the unnecessary ToString() is an actual override from object.ToString and removed it.
Hours of debugging later I noticed it. 

Please check that only the correct ToString() calls get removed.

**Comment by Rpinski** [comment]
I've added a check if called `ToString()` method actually overrides `object.ToString()` (directly or through overrides in base classes). That should help. Thanks for reporting!
