### ISSUE TITLE
Wrong usafe redundancy proposal

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#255]
I have:
```C#
public IntPtr Data {
	get {
		unsafe
		{
			return new IntPtr(DataPointer);
		}
	}
}
```
an getting a proposal for redundant "unsafe", which is not because if I remove it I will get:

>CS0214	Pointers and fixed size buffers may only be used in an unsafe context

**Comment by Alcatraz3222** [comment]
in that context the unsafe keyword is redundant, you're not dealing with unsafe context.

**Comment by Rpinski** [comment]
@FickoDeLux How and where is `DataPointer` declared?

**Comment by FickoDeLux** [comment]
Just after that like:
```C#
public unsafe byte* DataPointer
{
    get
    {
        ThrowIfDisposed();
        return NativeMethods.core_Mat_data(ptr);
    }
}
```

**Comment by Rpinski** [comment]
Should be fixed now and more longer mark it as redundant.

Thank you!
