### ISSUE TITLE
ContainsKey refactoring is repetitive, slow, and presumptuous

### ISSUE THREAD

**Issue by breyed** [icsharpcode/RefactoringEssentials#26]
Scott Hanselman [highlighted](http://www.hanselman.com/blog/VSRefactoringEssentialsFormerlyNR6PackFreeAnalyzersAndRefactoringForVisualStudio2015.aspx) the `ContainsKey` refactoring. There are three issues with this refactoring:

1. The result isn't DRY. The key is repeated in the `ContainsKey` call and the call to the dictionary indexer. This opens the door to bugs if one instance of the key is changed but not the other. Additionally, the cost of evaluating the key is doubled, which may be significant if not a simple literal.

2. Two dictionary lookup are required. Instead, the refactoring should generate `TryGetValue`.

3. The refactored code assumes that the proper response to a missing key is to do nothing. Somethings this is correct, but often not. Just as generated code for methods includes `throw new NotImplementedException()`, this refactoring should include code to throw an exception, which the user can replace with the appropriate handling logic or remove as appropriate.

**Comment by Rpinski** [comment]
HI Edward,

thank you for your suggestions. It makes sense to improve the output.

**Comment by mkrueger** [comment]
You're right.

/fixed - it's now using TryGetValue.

**Comment by breyed** [comment]
Great! The switch to `TryGetValue` takes care of my first two concerns. What a about generating code to handle when `TryGetValue` returns false? This situation is similar to the code generating for implementing methods of an interface. The code generator knows the methods must be there, but doesn't know what to put in them. I think leaving such flow paths empty creates a pitfall. Just like in the case of generating methods, generating code to throw an exception makes the new path more obvious and ensures that if there is a bug, it leads to a fast fail at runtime, rather than something subtle that takes a long time to track down.

**Comment by mkrueger** [comment]
It's arguable - I think it's a bit too much for that refactoring. Generating too much code is often an harassment for the users.

However depending on the knowledge level of the users it's a good idea to to generate an exception for the other path - or a bad one. It's hard to decide. I'll try to use that for a while to look for use cases for one solution or the other - sometimes these things need some time to evolve.

**Comment by breyed** [comment]
I agree it's subtle, and not obvious what is the best trade-off. I just noticed an existing practice counter-example to including code for an exception. If you type `override` and the name of a method, when VS inserts the method, it includes the call to the base class's method, but no exception; the method is generally blank. I think the assumption is that since it's just one method and you're right there, you'll likely right the code. This differs from implementing an interface, where several methods are generated at once.

In my experience, there will be an else case over half the time, so it would be nice to generate a placeholder for that, even though you can't predict what will be in it. Here's an idea I'll throw out. Generate this:

    if (a.TryGetValue(b))
        Foo();
    else
        ;

The last semicolon conveniently causes a compiler warning, which helps with avoiding forgetting, and it's code that will generally be needed anyway.
