### ISSUE TITLE
Every action is called twice if selected

### ISSUE THREAD

**Issue by stefandascalu64** [icsharpcode/RefactoringEssentials#260]
When creating a custom code fix, the code to perform the changes is called twice. 
This is not a problem for small changes but for bigger, solution wide changes this becomes a hassle.
There should be a way to disable preview of code fix change for more expensive operations or at least to not have it perform the call for solution wide changes. At the very least the preview should be canceled when the actual action is called.
Right now a solution wide check would take twice as long or require a more powerful machine with no real added benefit.

**Comment by Rpinski** [comment]
How exactly is this related to Refactoring Essentials? As I understand this is a suggestion for the Roslyn team?

**Comment by Rpinski** [comment]
Since there was no reply and the issue doesn't seem to be related to RE, I'll close this one for now.
