### ISSUE TITLE
VS15 Update 3 Support

### ISSUE THREAD

**Issue by biliciburak** [icsharpcode/RefactoringEssentials#261]
Hi, 

It's said that version 4.4.0.0 works under at least vs15 update2, though i've download and installed update3, it still does not work.
It's seen under tools=> extension and update but i can not use it at all. Is it a bug or do i miss something?

Thanks.

**Comment by Rpinski** [comment]
Please try with recently released VS 2017 RC. From what I see RE 4.4 works there. If not, please reopen this issue again.

**Comment by biliciburak** [comment]
Thx for your return but i dont have a chance to try it in vs17 rc mode, i need it to work on vs15 update3. but i guess it wont be possible.
