### ISSUE TITLE
The throw error with "NotImplementedException"

### ISSUE THREAD

**Issue by treenew** [icsharpcode/RefactoringEssentials#263]
1. In my code display:

> 警告	AD0001	分析器“RefactoringEssentials.CSharp.Diagnostics.RedundantUnsafeContextAnalyzer”抛出类型为“System.NotImplementedException”的异常，并显示消息“未实现该方法或操作。”。	

2.  How hideen all "RECS0004 Empty constructor is redundant" message?

**Comment by treenew** [comment]
3.How hideen any project all message in my solution(i.e., xxxxTests)?

**Comment by Rpinski** [comment]
Seems to be the same as https://github.com/icsharpcode/RefactoringEssentials/issues/259.
