### ISSUE TITLE
Question: Convert C# to Java and Swift?

### ISSUE THREAD

**Issue by RenniePet** [icsharpcode/RefactoringEssentials#267]
I'm wondering if the code converter part of this project could be used as the starting point for programs to convert C# to Java and Swift, respectively? 

Do you know of anyone who has tried, or of similar projects?

Thanks.

**Comment by siegfriedpammer** [comment]
As for our code converter: No, it cannot be used directly. You could use all the infrastructure available in Roslyn.
But keep in mind that Java and Swift have a completely different frameworks built around them, you might run into serious problems trying to convert larger projects.

Why not use C# on iOS/Android, i.e. Xamarin?
