### ISSUE TITLE
Refactors squiggly line missing: Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by BennieCopeland** [icsharpcode/RefactoringEssentials#278]
I have the 4.4.0 extension installed, and I've tried with the nuget package both installed and uninstalled. Should I be seeing a squiggly line notifying me of refactors? I tried the exact same code as in issue #194 , and while I get the potential refactors to merge the nested if statements, I do not get any notification neither visually in the editor or as a message/warning/error in the Error List.

Is this the expected behavior? If yes, how am I supposed to know what refactors there are in my code without Ctrl + . ing every line.

**Comment by siegfriedpammer** [comment]
For warnings VS should display the squiggly line and add an entry to the error list:
![grafik](https://cloud.githubusercontent.com/assets/344204/23100460/82d86ffc-f681-11e6-80fa-d032ecff0814.png)
![grafik](https://cloud.githubusercontent.com/assets/344204/23100462/996eb19a-f681-11e6-9d89-3029af6e1604.png)
Do you see any of that?

**Comment by BennieCopeland** [comment]
That I see. I'm talking about the optional code improvement refactorings. Like the "Add null check" refactoring. There is no visual indication suggesting this improvement. Neither a squiggly line nor error/warning/message in the errors list.

**Comment by siegfriedpammer** [comment]
It's intentional to only show them, when you press Ctrl+. as those are refactorings, not CodeFixes.

**Comment by BennieCopeland** [comment]
Ok. I was expecting something more like ReSharper's suggestions and hints. I'm closing this since it is working as designed.
