### ISSUE TITLE
ReplaceExplicitTypeWithVarCodeRefactoringProvider broken in Visual Studio 2017

### ISSUE THREAD

**Issue by rtlayzell** [icsharpcode/RefactoringEssentials#295]
| Product | Version |
|-|-|
| Refactor Essentials | 5.0.0.0 |
| Visual Studio | 2017 Community | 

Replacing explicit types is working perfectly well in Visual Studio 2015, however Visual Studio 2017, not so much.  Thought you should know.

**Code:**
```
List<int> list = new List<int>();
```
With the cursor over variable declaration type and selecting *Quick Actions and Refactorings* from either the context menu or using the shortcut <kbd>Ctrl</kbd> + <kbd>.</kbd> I'm expecting another context menu to pop up with the refactor in question available. 

I see no pop up.

**Comment by christophwille** [comment]
Please see

[https://github.com/icsharpcode/RefactoringEssentials/wiki/Feature-Set-Comparison-VS-2015-vs.-2017](https://github.com/icsharpcode/RefactoringEssentials/wiki/Feature-Set-Comparison-VS-2015-vs.-2017)

**Comment by rtlayzell** [comment]
So what you're saying is the conversion between explicit types and var should work out of the box in 2017?

**Comment by siegfriedpammer** [comment]
Yes

**Comment by christophwille** [comment]
For reference I took a screenshot:

![codestyle_vs2017](https://cloud.githubusercontent.com/assets/344208/23790784/dfcc1944-0580-11e7-81df-516b1ca2be86.png)

**Comment by rtlayzell** [comment]
Thanks, I've seen it and it doesn't seem to be working for me at all 😢 sad times.
