### ISSUE TITLE
VS2017 - Can't Convert

### ISSUE THREAD

**Issue by InteXX** [icsharpcode/RefactoringEssentials#317]
In VS2015, when I wanted to convert from C# to VB, I would:

1. Add a new .cs file to a VB project
2. Paste in some C# code
3. Save the file
4. Right-click the file
5. Select a context menu item to perform the conversion and copy the converted code to the clipboard

This behavior doesn't seem to be present in the VS2017 version. Has something changed?

I closed all instances of VS2017, installed the package, and then started VS2017.

**Comment by PhilSargeant** [comment]
Hello. Did you ever get a resolution to your question? I can convert using VS2015 but cannot see anything associated with Refactoring Essentials using VS2017.
Cheers

**Comment by InteXX** [comment]
@PhilSargeant — Alas, I did not. I'm still unable to convert with VS2017.

**Comment by PhilSargeant** [comment]
Thanks.
Seems no one knows or no one wants to talk about it - sad.

Sent from my iPad

On 11 Jul 2017, at 03:58, InteXX <notifications@github.com<mailto:notifications@github.com>> wrote:


@PhilSargeant<https://github.com/philsargeant> — Alas, I did not. I'm still unable to convert with VS2017.

**Comment by InteXX** [comment]
It almost seems as though the developers aren't monitoring this channel.

**Comment by GrahamTheCoder** [comment]
Thanks for the bug report. Apologies for the lack of communication, as of today I'm looking after the project in its new home, so I've duplicated the issue which can now be closed here. 
https://github.com/icsharpcode/CodeConverter/issues/17

I can't reproduce the issue. I see menu items, but then have problems loading some assemblies (https://github.com/icsharpcode/CodeConverter/issues/13). If anyone wishes to provide an [Activity Log](https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/) of the failure, it might help diagnosis.

**Comment by PhilSargeant** [comment]
Hello GrahamTheCoder,

I submitted this issue on July 8 2017. At that time the convert functionality of Refactoring Essentials in Visual Studio was definitely NOT working.

At some point towards the end of 2017 I installed an updated version of RefactoringEssentials and low and behold the conversion functionality appeared.

“My bad” for not having reflected this on GitHub.

Whatever was done solved the problem. Well done!

Cheers
Phil Sargeant

**Comment by InteXX** [comment]
What is the expected behavior/usage for this add-in? Is my original description correct?

I just reinstalled the add-in after a Windows user profile rebuild a couple of months ago. I'm still seeing the same behavior: no RefactoringEssentials-related items in the context menu when right-clicking on the .cs file in Solution Explorer.

I'm running VS Professional v15.5.2, with an anticipated update to v15.5.3 soon.

**Comment by InteXX** [comment]
I only just noticed the advice that CodeConverter has been spun off from RefactoringEssentials. I installed CodeConverter and was able to get the menu items I've been looking for.

Therefore, this issue is resolved. I'm getting other errors during conversion, but I'll post those in a new Issue at the CodeConverter repo.

Thanks for this great add-in. Keep up the good work.
