### ISSUE TITLE
AD0001 error in VSS2017 15.3.1

### ISSUE THREAD

**Issue by RachelDavids** [icsharpcode/RefactoringEssentials#326]
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantBaseQualifierAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`9' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'

**Comment by vishnu4** [comment]
I'm getting the same error in 15.3.5

**Comment by Rpinski** [comment]
Fixed with 3f5741730f5709705f52adc09d56e3a475b468eb.
