### ISSUE TITLE
Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantBaseQualifierAnalyzer' threw an exception...

### ISSUE THREAD

**Issue by jojorne** [icsharpcode/RefactoringEssentials#336]
Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantBaseQualifierAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`9' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'.

**Comment by Rpinski** [comment]
Fixed with 3f5741730f5709705f52adc09d56e3a475b468eb.
