### ISSUE TITLE
Move Code Converter to a Repository of its own

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/RefactoringEssentials#347]
Link to PR https://github.com/icsharpcode/RefactoringEssentials/pull/346

It is hard to discover, and maybe should have a repo (NuGet) of its own to be more easily discoverable, maintainable, evolvable. Today it is totally tied to RE, when initially it was seen as a "cross-selling".

@siegfriedpammer @Rpinski @grahamthecoder

**Comment by GrahamTheCoder** [comment]
Interesting thought. I assume you're suggesting:
* Pulling out the whole thing (not just the web app)
* Keeping the functionality integrated in RE via nuget for the cross sell
* Duplicating the small amount of shared code

I definitely discovered it through RE. 
I'm generally in favour of keeping things together until it's causing pain. Do you have an example of a problem caused by the status quo?

How would this compare to putting everything into a single VS solution?

**Comment by christophwille** [comment]
The idea goes like this: everything relating the code converter is pulled in a separate repo - that is code, tests, the web. The "Code Converter Nuget" is included in the VSIX project of RE to keep the existing functionality intact.

The main reason for the idea of separating it: no maintainer on RE. Minor reason: better visibility.

**Comment by christophwille** [comment]
@GrahamTheCoder obviously the move would impact your PR - which I'd prefer to include before.

**Comment by GrahamTheCoder** [comment]
If for some reason you do any history manipulation in the move, could you consider standardizing on either tabs or spaces. Here's some commands I used to do it on my pr recently if it helps at all https://grahamthecoder.wordpress.com/2017/12/03/rewriting-git-history/

**Comment by christophwille** [comment]
I tried yesterday / today, but a StackoverflowException in the unit tests stopped me dead in the tracks - plus the ILSpy 3.0 RTM process. I was able to cut down dependencies considerably.

**Comment by christophwille** [comment]
After long digging I found the reason for the StackoverflowException:

https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/Util/SymbolExtensions.cs#L449

Turns out there are other extension methods of the same name on other interfaces, and this then loops if you don't copy those files... 

I have attached a working copy (with definitely a bit too much in it, Util folder). The reference to the codefix has been inlined as the method that was interesting. All Roslyn reflection is out.

@siegfriedpammer please review, @GrahamTheCoder same please. Note that I haven't touched the namespaces (intentionally to easier find stuff for this exercise), nor the out-of-whack whitespace formatting.

[_.zip](https://github.com/icsharpcode/RefactoringEssentials/files/1572932/_.zip)

**Comment by christophwille** [comment]
I was thinking about the "shipping vehicle" for CC - two things gave me pause on sticking with RE:
* Depending on a currently maintainer-less project
* The Roslyn reflection requirements. Just about every time we upgraded ms.workspaces it broke. This doesn't bode well with item#1
So I am for including the vsix too as a shipping vehicle.

**Comment by christophwille** [comment]
Here is the updated zip: 
[_v2.zip](https://github.com/icsharpcode/RefactoringEssentials/files/1574744/_v2.zip)

**Comment by siegfriedpammer** [comment]
Just a few points for @GrahamTheCoder:
* please do not overuse `if expressions`, i.e., `? :`... the code should be readable for everyone. (see for example: (https://github.com/icsharpcode/CodeConverter/blob/edf411b72c053549f75ddf147a885934089afb81/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L684). This is too complex to grasp the semantics instantly.
* I had to fix a threading issue (see https://github.com/icsharpcode/CodeConverter/commit/edf411b72c053549f75ddf147a885934089afb81)

Thank you!

**Comment by christophwille** [comment]
Namespaces are adjusted for ics.codeconverter and tests. 

Vsix: I switched the Identity and package guids. But the entire extension has to be tested end-to-end (and no changes to namespaces or classes yet).

**Comment by christophwille** [comment]
https://github.com/icsharpcode/CodeConverter has now fully taken over. I still have to remove CC functionality here in RE and make the proper documentation adjustments to redirect to the new repo.

**Comment by GrahamTheCoder** [comment]
Apologies, I'll try to use if expressions only in very simple, concise cases from now on. I happen to find them much more readable than imperative code, but recognise that's not the general consensus amongst c# programmers.
Thanks for fixing the threading issue - I'll have a look.

**Comment by christophwille** [comment]
RE 5.6 is now published without the code converter bits (NuGet as well as VSIX).
