### ISSUE TITLE
RECS0092 - Convert field to readonly - static field and non-sattic constructor

### ISSUE THREAD

**Issue by Morcatko** [icsharpcode/RefactoringEssentials#37]
In this example the RECS0092 suggests to add readonly to StaticField. This will however break the build as static readonly fields can be written from static constructors only. The analyzer should consider if the field/constructor is static/instance

```
class SomeClass
{
	static int StaticField;
	public SomeClass()
	{
		StaticField = 1;
	}
}
```

**Comment by mkrueger** [comment]
fixed

**Comment by Morcatko** [comment]
The change probably fixed the issue when field is static and constructor is not. I have not tested it, but what about the case when both constructor and field are static? I guess the analyzer should recommend "readonly" as well.
The check should be something like "symbol.IsStatic == member.IsStatic"

```
class SomeClass
{
	readonly static int StaticField;
	readonly int Field;
	static SomeClass()
	{
		StaticField = 1;
	}

	public SomeClass()
	{
		Field = 1;
	}
}
```
