### ISSUE TITLE
Error when trying to access Quick Actions

### ISSUE THREAD

**Issue by jkarr** [icsharpcode/RefactoringEssentials#38]
When I press Ctrl + . to access the Quick Actions menu, an error is thrown.  Sometimes generic, and other times with a note to reference the Visual Studio reference log.  If I click on the light-bulb glyph, Visual Studio just crashes and closes.

I'm using Visual Studio 2015 RC, and RefactoringEssentials 1.1.0.0 (problem started after upgrade yesterday).  I'm coding in C#.

The stack trace in the activity log is:
System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.SyntaxAnnotation Microsoft.CodeAnalysis.Formatting.Formatter.get_Annotation()'. at RefactoringEssentials.CSharp.CodeRefactorings.GenerateSwitchLabelsCodeRefactoringProvider.<ComputeRefactoringsAsync>d__0.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at RefactoringEssentials.CSharp.CodeRefactorings.GenerateSwitchLabelsCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context) at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__7.MoveNext()

**Comment by christophwille** [comment]
The reason is 1.1 is built for VS 2015 RTM (that's why the other way around 1.0.x is having problems with RTM, because it was built for RC). Roslyn changed from RC to RTM.
