### ISSUE TITLE
Disable analysis of auto generated files

### ISSUE THREAD

**Issue by kempust** [icsharpcode/RefactoringEssentials#39]
I am getting warnings for auto generated files, e.g.

* Resources.Designer.cs
* .NETFramework,Version=v4.5.2.Assembly.Attributes.cs

Is it possible to provide a way to ignore certain files by name, I don't really want to add a global suppression file for every project in my solution

**Comment by Rpinski** [comment]
Which warnings do you see there? Usually analyzers ignore generated files. I also haven't seen any warnings when opening a usual project with some generated files (like Resources.Designer.cs or Settings.designer.cs).

**Comment by christophwille** [comment]
@kempust Do you have a repro for us? Because otherwise we'll close this issue.
