### ISSUE TITLE
VS 2015 RTM - Initialize field/property from ctor parameter is failing

### ISSUE THREAD

**Issue by Novakov** [icsharpcode/RefactoringEssentials#42]
1. I've got simple class like this: https://gist.github.com/Novakov/cea09c31c3b4b568e3f7
1. Place caret on ctor parameter param
1. Press Ctrl+. (quick actions)
1. Error bar appears: ``InitializeFieldFromConstructorParameterCodeRefactoringProvider encountered an error and has been disabled``

After some debugging I've found that https://github.com/icsharpcode/RefactoringEssentials/blob/bb25d62f8610d863a3bc639dc1924585bf4373c9/RefactoringEssentials/CSharp/CodeRefactorings/Synced/InitializeFieldFromConstructorParameterCodeRefactoringProvider.cs#L61 is throwing exception ``System.ArgumentException`` with message ``Node to track is not a descendant of the root``.

More debugging showed that lambda passed to ``CodeActionFactory.Create`` is called twice. First invocation works fine than, the second one, throws the exception. As an experiment I changed lambda to direct value (https://gist.github.com/Novakov/bf6e521506a4511e3401) and it worked. 

I'm using VS 2015 RTM (14.0.23107.0 D14REL). I'm able to reproduce this issue with release from VS Gallery, VSIX Gallery and manually built version (76a6b9583a42e77bfe6c2934c3d0c249994198c1).

**Comment by gluck** [comment]
Having this one as well, looks to me all refactorings from ctor are failing.
Activity log for exceptions on 2 tried refactorings can be found here: https://gist.github.com/gluck/e3b8f70ad37eaa3e343c

**Comment by mkrueger** [comment]
should be fixed.
