### ISSUE TITLE
RECS0143 in this[string key] when trying to throw ArgumentNullException for 'key'

### ISSUE THREAD

**Issue by samjudson** [icsharpcode/RefactoringEssentials#45]
I have the following code:

~~~
public string this[string key]
{
   set
   {
       if (key == null) throw new ArgumentNullException("key");
   }
}
~~~

This gives the following warning:

*RECS0143 - The parameter 'key' can't be resolved*

I'm pretty sure that this warning is incorrect. The Microsoft docs for Dictionary.Item property state that ArgumentNullException is thrown if key is null, so the above should be valid code. https://msdn.microsoft.com/en-us/library/9tee9ht2(v=vs.100).aspx

Anyone any ideas?

**Comment by mkrueger** [comment]
it's a bug 
/fixed

**Comment by samjudson** [comment]
I think that removes "value" as a valid parameter name does it not? I've got a pull request for this, as well as a new test.

**Comment by mkrueger** [comment]
value is no parameter for indexers.
