### ISSUE TITLE
RECS0022 Empty general catch clause

### ISSUE THREAD

**Issue by der-andy** [icsharpcode/RefactoringEssentials#47]
This warning show some weird behavior (at least IMHO).

```c#
public bool DoSomething()
{
    try
    {
        // ...
        return true;
    }
    catch
    {
        return false;
    }
}
```

In the above code sample, I get a warning that the empty general `catch` clause will suppress any errors, but this is not true, since the `catch` clause is not empty and errors won't be suppressed because of the return value. The suggested fix inserts `(Exception e)` behind the catch, but in the next line, so the code looks like this:

```c#
    catch
(Exception e)
    {
        return false;
    }
```

Surprisingly, the warning disappears although this doesn't change the behavior of my code, even if I remove the unnecessarily introduced variable `e`.

**Comment by Rpinski** [comment]
Warning should be fixed now. The inserted declaration in next line doesn't come from the analyzer, but from ``AddCatchExceptionCodeRefactoringProvider`` -> will be fixed, too.
