### ISSUE TITLE
C# - GeneratePropertyAction

### ISSUE THREAD

**Issue by Novakov** [icsharpcode/RefactoringEssentials#49]
I'm going to try port GeneratePropertyAction. I see that there are some ignored test for that action, so I'll treat them as starting point.

**Comment by Novakov** [comment]
I think I can't assign myself as I'm not member of this project :)

**Comment by Rpinski** [comment]
Yes, that's right. I'll assign myself here to "protect" the issue and you are free to work on it and finally create a pull request.

Thank you for participating!

**Comment by Novakov** [comment]
Just realized... Isn't Roslyn's Encapsule field refactoring (https://github.com/dotnet/roslyn/tree/master/src/Features/CSharp/EncapsulateField) doing the same thing GenerateProperty is supposed to do?

If so, is this issue still relevant?

**Comment by Rpinski** [comment]
Ah, you're right: Roslyn's "Encapsulate field" refactoring is doing almost the same. Ok, then I'll close this issue, but there are still more possible refactorings that would need a port :-)
