### ISSUE TITLE
Extract class to new file in VB

### ISSUE THREAD

**Issue by petterek** [icsharpcode/RefactoringEssentials#51]
This is the refactoring I'm using the most in R#....

**Comment by petterek** [comment]
<ExportCodeRefactoringProvider(LanguageNames.VisualBasic, Name:=NameOf(MoveClassToFileCodeRefactoringProvider)), [Shared]>
    Friend Class MoveClassToFileCodeRefactoringProvider
    Inherits CodeRefactoringProvider

    Public NotOverridable Overrides Async Function ComputeRefactoringsAsync(context As CodeRefactoringContext) As Task
        ' TODO: Replace the following code with your own analysis, generating a CodeAction for each refactoring to offer

        Dim root = Await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(False)

        ' Find the node at the selection.
        Dim node = root.FindNode(context.Span)

        ' Only offer a refactoring if the selected node is a type statement node.
        Dim typeDecl = TryCast(node, ClassStatementSyntax)
        If typeDecl Is Nothing Then
            Return
        End If

        'Dim ClassName As String = 
        Dim toRemove As ClassBlockSyntax = CType(typeDecl.Parent, ClassBlockSyntax)
        Dim ClassName As String = typeDecl.Identifier.GetIdentifierText

        Dim a2 = CodeAction.Create($"Move class to file '{ClassName}.vb'", Function(c) MoveClassToFile(context.Document, toRemove, ClassName, c))

        ' Register this code action.
        context.RegisterRefactoring(a2)

    End Function

    Private Async Function MoveClassToFile(document As Document, typeDecl As ClassBlockSyntax, className As String, cancellationToken As CancellationToken) As Task(Of Solution)

        'Dim identifierToken = typeDecl.Identifie

        Dim SemanticModel = Await document.GetSemanticModelAsync(cancellationToken)
        Dim typeSymbol = SemanticModel.GetDeclaredSymbol(typeDecl, cancellationToken)

        Dim currentSyntaxTree = document.GetSyntaxTreeAsync().Result
        Dim currentRoot = currentSyntaxTree.GetRootAsync().Result
        Dim replacedRoot = currentRoot.RemoveNode(typeDecl, SyntaxRemoveOptions.KeepNoTrivia)

        Dim changedDocument = document.WithSyntaxRoot(replacedRoot)

        'newDDocument = RemoveUnusedImportDirectivesAsync

        'Dim currentUsings = currentRoot.DescendantNodesAndSelf().Where(Function(node) TypeOf (node) Is UsingDirectiveSyntax)

        'Dim addedDocument = document.Project.AddDocument( String.Format("{0}.vb", typeDecl.ChildNodesAndTokens(0).AsNode.GetText), SourceText.From(typeDecl.ToFullString()), document.Folders)
        Dim addedDocument = changedDocument.Project.AddDocument(String.Format("{0}.vb", className), typeDecl.GetText, document.Folders)

        Return addedDocument.Project.Solution
    End Function
    End Class

This is a very rudamentary implementation done in VB.

**Comment by Rpinski** [comment]
Hi petterek,

Thank you for your suggestion. Could you imagine implementing that as a pull request? But 2 things are important: Implementation must be in C# (since all RE is C#, even VB refactorings) and there must be unit tests.

Of course, you can ask us if you need any help.

**Comment by petterek** [comment]
I will give it a go. I sure need some help with the unittests..

**Comment by erdmenchen** [comment]
So what about the status here? 
I´d love to see this new refactoring, since its one of the basic refactorings you do all the time in legacy code...

**Comment by ctolkien** [comment]
I'd like to see this for C# projects too (doesn't seem to currently exist?)

**Comment by Rpinski** [comment]
There was a pull request for that already (https://github.com/icsharpcode/RefactoringEssentials/pull/66) and @petterek has been working on it, but currently it seems to be unfinished (?).

**Comment by petterek** [comment]
That is correct, I have not been working on it for a while.

**Comment by reecebradley** [comment]
+1

**Comment by siegfriedpammer** [comment]
closing because it is provided by VS 2017 out-of-the-box.
