### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/RefactoringEssentials#52]
Technical FAQ for contributors will go to the wiki (easier to maintain, don't pollute repo with screenshots et al). Those wiki articles should contain links to getting started guides, conference videos, samples, SO posts, blog posts, MSDN articles, as well as a ramp up from simple to more complicated in our own codebase.

https://github.com/icsharpcode/RefactoringEssentials/wiki/Contributing-to-Analyzers-and-Code-Fixes
https://github.com/icsharpcode/RefactoringEssentials/wiki/Contributing-to-Refactorings

The .md: a welcome to everyone, from users to bug reporter to devs writing new analyzers/refactorings.

Maybe http://contributor-covenant.org/

**Comment by Rpinski** [comment]
Meanwhile we have added a collection of helping links to wiki und sample analyzer/refactoring implementations to repo.
