### ISSUE TITLE
C# - MergeNestedIfAction

### ISSUE THREAD

**Issue by Novakov** [icsharpcode/RefactoringEssentials#56]
MergeNestedIfAction looks like not implemented and not provided by Roslyn, so I'll try to implement this one.

**Comment by Rpinski** [comment]
Great, thank you.

**Comment by Novakov** [comment]
Pull request: https://github.com/icsharpcode/RefactoringEssentials/pull/57

**Comment by mkrueger** [comment]
Merged. Thanks
