### ISSUE TITLE
Do not treat redundant syntax as warning

### ISSUE THREAD

**Issue by Peter-Juhasz** [icsharpcode/RefactoringEssentials#58]
Green wavy underline indicating redundant syntax is too intrusive. These cases should not count as warnings, only possibilities for simplification of the source code at syntax level. Remove underline and keep only dimming like built-in analyzers do.

Some fixes are even contradictory with the Microsoft coding guidelines. For example, one of the rules states: always write access modifiers explicitly even if it is 'private' or 'internal'.
![intrusive redundant syntax](https://cloud.githubusercontent.com/assets/9047283/9027858/87c4764e-3965-11e5-9789-9d3c8d950d04.PNG)

Or another case, initialization of an array should not be treated as a warning:
![intrusive array](https://cloud.githubusercontent.com/assets/9047283/9027884/a773ea0a-3966-11e5-8749-dedbf906efd3.PNG)

Please decrease the diagnostic severity from warning but keep the 'unnecessary' custom tag in the redundant syntax analyzers.

**Comment by mkrueger** [comment]
Didn't know that it looks like that in VS - I now changed the severity to info.
