### ISSUE TITLE
InvertIfCodeRefactoringProvider: InvalidOperationException on nested "if ... if ... else"

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/RefactoringEssentials#62]
The code

```cs
    class TestClass
    {
        int TestMethod(int a)
        {
            if (a > 0)
                if (a < 5)
                {
                    return 1;
                }
                else
                {
                    return 2;
                }

            return 0;
        }
    }
```

and Ctrl+. at ``if (a < 5)`` makes ``InvertIfCodeRefactoringProvider`` crash with

*An exception of type 'System.InvalidOperationException' occurred in Microsoft.CodeAnalysis.CSharp.dll but was not handled in user code*

*Additional information: The item specified is not the element of a list.*

at
https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/CodeRefactorings/Synced/InvertIfCodeRefactoringProvider.cs#L44

**Comment by mkrueger** [comment]
fixed.
