### ISSUE TITLE
ConvertIfStatementToReturnStatementAction crashes on "if" without "else"

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/RefactoringEssentials#63]
The code

```cs
    class TestClass
    {
        int TestMethod(int a)
        {
            if (a > 0)
                if (a < 5)
                {
                    return 1;
                }

            return 0;
        }
    }
```

and ``Ctrl+.`` at ``if (a < 5)`` makes ``ConvertIfStatementToReturnStatementAction `` crash with a yellow "... encountered an error and has been disabled" bar.

**Comment by Rpinski** [comment]
Exception is ``ArgumentOutOfRangeException``:

*Specified argument was out of the range of valid values.*
*Parameter name: position*

At:
https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/CodeRefactorings/Uncategorized/ConvertIfStatementToReturnStatementAction.cs#L70

**Comment by mkrueger** [comment]
fixed.
