### ISSUE TITLE
RECS0033 Suggestion produces bad code in Fix

### ISSUE THREAD

**Issue by swhaworth** [icsharpcode/RefactoringEssentials#69]
The code:

    if(args.TargetNode != null)
    {
        args.TargetNode.Expanded = true;
    }

produces a suggestion RECS0033 Replace with '|='.

Doing the fix produces:

    args.TargetNode.Expanded |= args.TargetNode != null;

as you can see, the original intent of only expanding a non-null `args.TargetNode` now produces a `NullReferenceException` if `args.TargetNode` is null instead of just not setting the Expanded property.

I don't know if you can expand the suggestion template to account for this or whether it is just something the user needs to be wary of, but I thought I would share.

**Comment by Rpinski** [comment]
I'll check that. Looks more like a bug to me, because actually there should be support for this case already. There is even a unit test for such a null check situation:

https://github.com/icsharpcode/RefactoringEssentials/blob/master/Tests/CSharp/Diagnostics/ConvertIfToOrExpressionTests.cs#L227
