### ISSUE TITLE
Inappropriate frameworkReference

### ISSUE THREAD

**Issue by bradwilson** [icsharpcode/RefactoringEssentials#88]
I'm not sure why this is here:

https://github.com/icsharpcode/RefactoringEssentials/blob/f7732ff0250781082e61089bfbc2788d26241b85/RefactoringEssentials/RefactoringEssentials.nuspec#L19

Since this isn't a library, you shouldn't be specifying dependent assemblies. This manifests as a compiler warning for `dotnet` projects.

**Comment by Rpinski** [comment]
Hmm, not sure where it came from, maybe from a diagnostic analyzer project template from early VS 2015 CTP days.
