### ISSUE TITLE
Does RefactoringEssentials support code completion like NR5 did?

### ISSUE THREAD

**Issue by lukebuehler** [icsharpcode/RefactoringEssentials#90]
Going forward, I'd like to use Roslyn's code completion features, but they are all internal. Does RefactoringEssentials support any code completion stuff or have any plans to?

**Comment by christophwille** [comment]
http://mikemdblog.blogspot.co.at/2015/07/the-end-of-nrefactory-6.html

(plus https://github.com/icsharpcode/SharpDevelop/issues/695 to not propagate the "discontinued" thing again)

**Comment by lukebuehler** [comment]
Got it, so it's either use NRefactory 5 code completion, which is what SharpDevelop 5 uses, or use straight Roslyn and my own hacks to access code completion from there.

**Comment by christophwille** [comment]
With the hacks going away over time, yes.
