### ISSUE TITLE
RECS0033 is incorrectly raised

### ISSUE THREAD

**Issue by 0x084E** [icsharpcode/RefactoringEssentials#96]
The following code raises RECS0033:

if (this.itemsListView.Items.Count > 0)
{
this.itemsListView.Items[0].Selected = true;
}

where itemsListView is a WinForms ListView. I was not able to reproduce this with a List<T> or Array, so maybe this is related to the list type?!?

**Comment by Rpinski** [comment]
I could reproduce it with official 1.2 release, but not with latest development build. I assume this is the same reason as in issue #69, which is already fixed for next release. Therefore I'll close this one.

BTW: To test the latest development build, you can try the release from [VSIX Gallery](http://vsixgallery.com/extension/NR6Pack.Refactorings.Vsix..cd27e59b-5c56-4238-8931-c9bb745a7a7f/).

**Comment by 0x084E** [comment]
Confirmed to be fixed in the latest bits. Thanks!
