### ISSUE TITLE
Error List in separate window loses responsiveness

### ISSUE THREAD

**Issue by SeanSobey** [icsharpcode/RefactoringEssentials#99]
It seems that if you run the Error List window as a separate window (not docked in the main VS tab by default), after you navigate to a few of the refactor warnings the window no longer responds to input. Running in the default window layout is fine and running a separate Error List without the plugin active works fine.

**Comment by christophwille** [comment]
That however is some VS bug, and you should report it to Microsoft.

**Comment by SeanSobey** [comment]
Thanks, I sent a bug report to them.
